### ISSUE TITLE
[Prefect Orion] Can't connect to Orion API at xxx. Check that it's accessible from your machine.

### ISSUE THREAD

**Issue by Hongbo-Miao** [PrefectHQ/prefect-helm#101]
# Experiment 1 (Succeed)

I tried to deploy Prefect Orion in Kubernetes.

1. Create **my-values.yaml**
    
    ```yaml
    postgresql:
      auth:
        password: passw0rd
    ```

2. Run

    ```shell
    helm repo add prefect https://prefecthq.github.io/prefect-helm
    
    helm install \
      prefect-orion \
      prefect/prefect-orion \
      --namespace=hm-prefect \
      --create-namespace \
      --values=my-values.yaml
    
    kubectl port-forward service/prefect-orion --namespace=hm-prefect 4200:4200
    ```

When I open http://localhost:4200, everything looks good.

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/3375461/209922271-10c8245c-8c7e-4443-8352-75f00fe4af76.png">

# Experiment 2 (Having Issue)

This time only port forwards to a different port.

1. Create **my-values.yaml**
    
    ```yaml
    postgresql:
      auth:
        password: passw0rd
    ```

2. Run

    ```shell
    helm repo add prefect https://prefecthq.github.io/prefect-helm
    
    helm install \
      prefect-orion \
      prefect/prefect-orion \
      --namespace=hm-prefect \
      --create-namespace \
      --values=my-values.yaml
     
    # Note here, only port forwards to a different port, internally it still uses 4200.
    kubectl port-forward service/prefect-orion --namespace=hm-prefect 48838:4200
    ```

When I open http://localhost:48838, I got error in the UI

> Can't connect to Orion API at http://127.0.0.1:4200/api. Check that it's accessible from your machine.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/3375461/209920314-db9b087b-6426-415c-b346-754e29adea5d.png">

I feel the UI should use DNS name to contact the server, which is why I did next experiment 3.

# Experiment 3 (Having Issue)

This time set the DNS name.

1. Create **my-values.yaml**
    
    ```yaml
    orion:
      env:
        - name: PREFECT_API_URL
          value: http://prefect-orion.hm-prefect.svc:48838/api
    
    service:
      port: 48838
    
    postgresql:
      auth:
        password: passw0rd
    ```

2. Run

    ```shell
    helm repo add prefect https://prefecthq.github.io/prefect-helm
    
    helm install \
      prefect-orion \
      prefect/prefect-orion \
      --namespace=hm-prefect \
      --create-namespace \
      --values=my-values.yaml
    
    kubectl port-forward service/prefect-orion --namespace=hm-prefect 48838:48838
    ```

When I open http://localhost:48838 , I got error in the UI

> Can't connect to Orion API at http://prefect-orion.hm-prefect.svc:48838/api. Check that it's accessible from your machine.

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/3375461/209919086-946c4e30-b01e-43da-9df2-3a321cd60e16.png">

Any idea why failed to use a different port? Thanks! 😃

**Comment by Hongbo-Miao** [comment]
I did one more experiment. This time only port forwards to a different port, internally it still uses 4200.

1. Create **my-values.yaml**
    
    ```yaml
    postgresql:
      auth:
        password: passw0rd
    ```

2. Run

    ```shell
    helm repo add prefect https://prefecthq.github.io/prefect-helm
    
    helm install \
      prefect-orion \
      prefect/prefect-orion \
      --namespace=hm-prefect \
      --create-namespace \
      --values=my-values.yaml
     
    # Note here, only port forwards to a different port, internally it still uses 4200.
    kubectl port-forward service/prefect-orion --namespace=hm-prefect 48838:4200
    ```

When I open http://localhost:48838/flow-runs , I got error in the UI

> Can't connect to Orion API at http://127.0.0.1:4200/api. Check that it's accessible from your machine.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/3375461/209920314-db9b087b-6426-415c-b346-754e29adea5d.png">

**Comment by Hongbo-Miao** [comment]
I feel the UI should use DNS name to contact the server. However, in my Experiment 1, I did set DNS name

```yml
orion:
  env:
    - name: PREFECT_API_URL
      value: http://prefect-orion.hm-prefect.svc:48838/api
```

in **my-values.yaml**.

So now sure causes the issue.

**Comment by jawnsy** [comment]
Hello there,

Thanks for creating this issue.

Your Prefect API URL needs to be a hostname accessible by clients (browsers, the Prefect CLI, agents, and flows). Since you're using port-forward to access the service over localhost, you will need to ensure that the API URL is set to a URL accessible by your local machine.

In your third example, try:

```
orion:
  env:
    - name: PREFECT_API_URL
      value: http://localhost:48838/api
```

This port should match the host/port you use in your browser. This will then only be accessible by people with the same permission to port-forward to the service, as you've done.

Alternative ways to bring traffic into the cluster include configuring a LoadBalancer service or Ingress, but these are outside the scope of what we can support here. You will need to consult your specific cloud documentation to understand how these work and the tradeoffs involved. For example, see [Google Kubernetes Engine Ingress](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress) or [Amazon Elastic Kubernetes Service Ingress](https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html).
