### ISSUE TITLE
`publicApiUrl` does not work, while `PREFECT_ORION_UI_API_URL` works

### ISSUE THREAD

**Issue by Hongbo-Miao** [PrefectHQ/prefect-helm#113]
I found is that if I use `publicApiUrl` based on https://github.com/PrefectHQ/prefect-helm/blob/5c56dea3558789f8fcc56cee80c18c0efffaf3a6/charts/prefect-orion/values.yaml#L35-L36

it won't work:

```yaml
orion:
  publicApiUrl: http://localhost:4200/api
  env:
    - name: PREFECT_API_URL
      value: http://prefect-orion.hm-prefect.svc:4200/api
postgresql:
  auth:
    # username: prefect
    password: passw0rd
```

It will give me the error

> Can't connect to Orion API at http://prefect-orion.hm-prefect.svc:4200/api. Check that it's accessible from your machine.

When I open http://localhost:4200

<img width="1493" alt="image" src="https://user-images.githubusercontent.com/3375461/216621376-65c083a4-8119-46b9-8d32-f38c77559fd0.png">

Using `PREFECT_ORION_UI_API_URL` works

```yaml
orion:
  env:
    - name: PREFECT_API_URL
      value: http://prefect-orion.hm-prefect.svc:4200/api
    - name: PREFECT_ORION_UI_API_URL
      value: http://localhost:4200/api

postgresql:
  auth:
    password: passw0rd
```
