### ISSUE TITLE
Is `publicApiUrl` for `PREFECT_API_URL` or `PREFECT_ORION_UI_API_URL`?

### ISSUE THREAD

**Issue by Hongbo-Miao** [PrefectHQ/prefect-helm#115]
Before I have

**my-values.yaml**

```yaml
orion:
  env:
    - name: PREFECT_API_URL
      value: http://prefect-orion.hm-prefect.svc:4200/api
    - name: PREFECT_ORION_UI_API_URL
      value: http://localhost:4200/api

postgresql:
  auth:
    password: passw0rd
```

and it works.

I found `publicApiUrl` [here](https://github.com/PrefectHQ/prefect-helm/blob/5c56dea3558789f8fcc56cee80c18c0efffaf3a6/charts/prefect-orion/values.yaml#L35-L36).

However, I am confused for the naming.

`publicApiUrl` seems replacing `PREFECT_API_URL`.

But based on the [comment](https://github.com/PrefectHQ/prefect-helm/blob/5c56dea3558789f8fcc56cee80c18c0efffaf3a6/charts/prefect-orion/values.yaml#L35-L36):

```yaml
 # -- sets PREFECT_ORION_UI_API_URL; should be publicly accessible API URL; UI will not work unless set 
 publicApiUrl: "" 
```

`publicApiUrl` seems replacing `PREFECT_ORION_UI_API_URL`.

Is `publicApiUrl` to replace `PREFECT_API_URL` or `PREFECT_ORION_UI_API_URL`? Please clarify, thanks! 😃

**Comment by AmyAiyyoi** [comment]
Thanks for raising the question!
And yes, `publicApiUrl` is supposed to provide value for `PREFECT_ORION_UI_API_URL`.
On the other hand, value in [here](https://github.com/PrefectHQ/prefect-helm/blob/5c56dea3558789f8fcc56cee80c18c0efffaf3a6/charts/prefect-agent/values.yaml#L67-L69) 
```yaml
orionApiConfig:
    # -- prefect API url (PREFECT_API_URL); should be in-cluster URL if the agent is deployed in the same cluster as the API
    apiUrl: http://127.0.0.1:4200/api

```
is supposed to set `PREFECT_API_URL` in this [code block](https://github.com/PrefectHQ/prefect-helm/blob/5c56dea3558789f8fcc56cee80c18c0efffaf3a6/charts/prefect-agent/templates/deployment.yaml#L71-L72):
``` yaml
- name: PREFECT_API_URL
  value: {{ template "agent.apiUrl" . }}
```



And I would like to quote @madkinsz when I learned about the different usage of these two URLs:

> `PREFECT_ORION_UI_API_URL` should be used in the container hosting the UI to the publicly accessible API URL so when users are using the UI their browser can contact the API

> `PREFECT_API_URL` should be used in containers that need to contact the API such as the agent. This can be the in-cluster API URL.

> `PREFECT_ORION_UI_API_URL` defaults to `PREFECT_API_URL` for convenience for our users running the API locally. That convenience is confusing once you’re on Kubernetes and we should be explicit about which one we are setting.

Let us know if you have more questions.
