### ISSUE TITLE
 How to use external Postgres when deploy by Helm Chart?

### ISSUE THREAD

**Issue by Hongbo-Miao** [PrefectHQ/prefect-helm#127]
Originally asked at https://discourse.prefect.io/t/how-to-use-external-postgres-when-deploy-by-helm-chart/2501/1
Here is a copy:

---

When deploy Prefect Server into Kubernetes by Helm Chart, I can disable default Postgres by changing [this](https://github.com/PrefectHQ/prefect-helm/blob/e158acaf8e84a23154c1a6f0b051a33ff45908d3/charts/prefect-server/values.yaml#L217-L218) to

```yaml
postgresql:
  enabled: false
```
Next step, I am trying to point to a existing Postgres, however, I didn’t find any info in the Helm chart.

Any guide would be appreciate. Thanks! :smiley:

**Comment by gabcoyne** [comment]
Hey Hongbo, the field postgresql.externalHostname is used to define the hostname for your external postgres database, then set postgresql to disabled and fill in all of the credential fields.

**Comment by Hongbo-Miao** [comment]
Thanks @gabcoyne !

For example, I have a database at `http://postgres-service.hm-postgres.svc:5432`.

I tried

```shell
helm install \
  prefect-server \
  prefect/prefect-server \
  --namespace=hm-prefect \
  --create-namespace \
  --values=my-values.yaml
```

my-values.yaml

```yaml
server:
  publicApiUrl: https://xxx.com/api
postgresql:
  enabled: false
  auth:
    username: admin
    password: passw0rd
  externalHostname: postgres-service.hm-postgres.svc
```

Is this correct?

I did set `enabled: false`, But Prefect Server helm chart still created a Postgres. Any idea? Thanks!

<img width="666" alt="image" src="https://user-images.githubusercontent.com/3375461/224451079-8f8b6a3d-1ab1-4e1c-a7cf-2ff8186667b7.png">

**Comment by Hongbo-Miao** [comment]
Finally found a solution posted at https://discourse.prefect.io/t/how-to-use-external-postgres-when-deploy-by-helm-chart/2501/6

Here is a copy:

---

Thanks @George_Coyne and @jwlarocque !

The [helm values](https://github.com/PrefectHQ/prefect-helm/tree/main/charts/prefect-server#values) are quite confused, it turns out I actually only need set two values:

![image|562x500](upload://seeiMHcQL12MwpcyVsKTX7KzI0O.png)

Here is my final solution to use external Postgres host.

Assuming my Postgres host is  `postgres-service.hm-postgres.svc`, port is `5432`, username is `admin`, password is `passw0rd`.

First, I need create a secret, and this secret has to be in same namespace with Prefect Server.

```shell
kubectl create secret generic hm-prefect-postgres-secret \
  --namespace=hm-prefect \
  --from-literal="connection-string=postgresql+asyncpg://admin:passw0rd@postgres-service.hm-postgres.svc:5432/hm_prefect_db"
```

Then, I can deploy Prefect Server by:

```
helm install \
  prefect-server \
  prefect/prefect-server \
  --namespace=hm-prefect \
  --create-namespace \
  --values=my-values.yaml
```

**my-values.yaml**
```yaml
server:
  publicApiUrl: https://prefect.example.com/api
postgresql:
  useSubChart: false
  auth:
    existingSecret: hm-prefect-postgres-secret
```

Hopefully it helps save people some time in future! :smiley:
