### ISSUE TITLE
semver - prefect-agent helm chart should use semver releases (instead of dates)

### ISSUE THREAD

**Issue by ilievlad** [PrefectHQ/prefect-helm#156]
The current release numbers being dates don't agree well with dependency getter bots like renovate or the fluxcd auto update feature.

After further investigation, it seems that the change to use a zero trailing for month has broken the dependency autoupdate.

**Comment by jamiezieziula** [comment]
Hi @ilievlad - do you mean that 2023.4.20 (instead of 2023.04.20) would fix your problem?

At this time, we are committed to continue using DateVer.  You could investigate a tool like [updatecli](https://www.updatecli.io/) to manage your dependency updates for the helm releases if fluxcd auto update doesnt work for you.

sample manifest.yaml below:
```yaml
sources:
  prefect-agent:
    kind: helmchart
    spec:
      url: https://prefecthq.github.io/prefect-helm
      name: prefect-agent
conditions: {}
targets:
  prefect-agent:
    name: bump chart dependencies
    kind: yaml
    spec:
      file: path/to/helmrelease/prefect-agent.yaml
      key: spec.chart.spec.version
    sourceid: prefect-agent
```
