### ISSUE TITLE
unable to connect local runs to ingress api

### ISSUE THREAD

**Issue by jacksund** [PrefectHQ/prefect-helm#176]
I'm able to get the web ui working properly with these custom settings:

``` yaml
server:
  publicApiUrl: "https://example.com/api"
ingress:
  enabled: true
  host:
    hostname: example.com
postgresql:
  auth:
    password: "prefect"
```

However, when I try to connect to the API from my local laptop I keep getting failed connection errors:
```
RuntimeError: Cannot create flow run. Failed to reach API at https://example.com/api/.
```
(after running `prefect config set PREFECT_API_URL=https://example.com/api/`)

Is there a step that I'm missing here? There's no example `yaml` file in this repo's README, so it's difficult know if I'm on the right track. Seems like [this user](https://discourse.prefect.io/t/unable-to-get-cli-tools-to-connect-to-api-even-though-ui-is-working/1967) had a similar issue but no answer was ever posted.

Thanks in advance for any help 😄
