### ISSUE TITLE
Ingress not working as expected

### ISSUE THREAD

**Issue by HasnainRaz** [PrefectHQ/prefect-helm#191]
Hello,

I am using minikube to deploy the prefect-agent and server to my minikube k8s cluster. My goal is to NOT use prefect cloud, I want to completely self host a prefect server and agent on k8s.
These examples assume I am deploying to a k8s namespace called: my-namespace
First I setup minikube with nginx ingress as:
```bash
minikube start
minikube addons enable ingress
```

Then I update the following values for each helm chart in the values.yaml:
For Prefect Server:
```
namespaceOverride: "my-namespace"
server:
    publicApiUrl: "http://127.0.0.1:4200/api"
postgresql:
    password: "prefect"
```

For the Agent:
```
namespaceOverride: "my-namespace"
agent:
    apiConfig: "server"
    serverApiConfig:
        apiUrl: http://prefect-server.my-namespace.svc.cluster.local:4200/api
serviceAccount:
     create: false
```

Then I use helm to deploy (building dependency list might be required for postgres here):
```bash
helm install -f prefect-server/values.yaml prefect-server ./prefect-server -n my-namespace
helm install -f prefect-agent/values.yaml prefect-agent ./prefect-agent -n my-namespace
```
Then I use port forwarding:
```bash
kubectl get pod -n my-namespace
kubectl port-forward pod/{prefect-server-pod-name} 4200:4200 -n my-namespace
```

Then I go to 127.0.0.1:4200 in my browser, and I see the prefect UI, everything is fine. I get no errors, I can view all blocks and my default work queue is healthy. I've also inspected the logs of all my pods and see no errors. Great!

Now I would like to get rid of the port forwarding, such that I can use ingress to navigate to the prefect UI, so I change the prefect-server values to the following:
```
namespaceOverride: "my-namespace"
server:
    publicApiUrl: "http://127.0.0.1:4200/api"
postgresql:
    password: "prefect"
ingress:
    enabled: true
    host:
        hostname: prefect.example.com
    annotations: {"kubernetes.io/ingress.class": "nginx"}
```
I then upgrade my release with the values from above:
```
helm upgrade -f prefect-server/values.yaml prefect-server ./prefect-server -n my-namespace
```

Then I navigate to "prefect.example.com" and the page is unavailable: "This site can't be reached".

How do I set the ingress correctly? What am I doing wrong?

**Comment by HasnainRaz** [comment]
Ok, I found two mistakes:
The first one:
```
namespaceOverride: "my-namespace"
server:
    publicApiUrl: "http://prefect.example.com/api"
postgresql:
    password: "prefect"
ingress:
    enabled: true
    host:
        hostname: prefect.example.com
    annotations: {"kubernetes.io/ingress.class": "nginx"}
```
The host name should also be the URL. This still doesn't work, but that is because of minikube. My machine is routing traffic between internet. If i edit my hosts file to allow the URL, it works.
Also tried it on a real cluster, seemed to work.

Closing
