### ISSUE TITLE
ArgoCD does not recognize this repo as a chart repo and path cannot resolve targetRevision

### ISSUE THREAD

**Issue by darnone-sr** [PrefectHQ/prefect-helm#197]
ArgoCD does not recognize the repo as a valid Chart repo because if missing index.yaml. Tried using path in ArgoCD application  path but the targetRevision complains "Unable to resolve '2023.6.22' to a commit SHA"

**Comment by jamiezieziula** [comment]
@darnone-sr - can you try the tag `2023.06.22`?

**Comment by darnone-sr** [comment]
Here is what we have in the ArgoCD application:

```
project: default
  source:
    repoURL: https://github.com/PrefectHQ/prefect-helm
    path: charts//prefect-server
    targetRevision: 2023.6.22
    helm:
      parameters:
.
.
.
```

ArgoCD reponds with:
`ComparisonError. rpc error: code = Unknown desc = Unable to resolve '2023.6.22' to a commit SHA`

path is used instead of chart because ArgoCD detects the git repo is not a chart repo - missing index.yaml.
