### ISSUE TITLE
Unable to start worker

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect-helm#200]
Given values-worker.yaml:
```yaml
worker:
  image:
    prefectTag: 2.10.21-python3.10

  config:
    workPool: kubes-pool

  apiConfig: server

  serverApiConfig:
    apiUrl: http://prefect-server:4200/api
```

Deploy the prefect-worker chart:
```bash
helm upgrade --install prefect-worker prefect/prefect-worker --version=2023.07.13 --values values-worker.yaml --wait --debug
```

Check the logs and observe:

```
❯ kubectl logs -l "app.kubernetes.io/name in (prefect-worker)" -f --tail=-1
Unable to start worker. Please ensure you have the necessary dependencies 
installed to run your desired worker type.
```
