### ISSUE TITLE
Add `workQueues` to prefect-worker Helm values

### ISSUE THREAD

**Issue by Daveography** [PrefectHQ/prefect-helm#211]
Looking to be able to configure which work queues the worker pulls from via Helm values, like we are currently able to do with prefect-agent. E.g.,

```yaml
spec:
  values:
    worker:
      config:
        workQueues:
          - my-work-queue
```

Thanks!
