### ISSUE TITLE
Ignore values.schema.json ?

### ISSUE THREAD

**Issue by brks-rssll** [PrefectHQ/prefect-helm#258]
The recently added values.schema.json makes integration into an a wider, existing infrastructure process more difficult. I need to have global parameters passed through as well as, for example, storageClass for the postgres persistence. So I have to maintain a local version of prefect-helm charts and delete values.schema.json.

**Comment by gyu11** [comment]
I am also having an issue where I can't include the prefect charts as a subchart with the introduction of the values.schema.json.

```
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
prefect-server:
- (root): Additional property global is not allowed
```

You can reproduce this by creating an empty chart that tries to deploy the prefect-server chart as a subchart with default values. Here is an example Charts.yaml:
```
apiVersion: v2
name: example-parent-chart
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: prefect-server
    version: "2023.10.17"
    repository: https://prefecthq.github.io/prefect-helm
```

I do not see the error using the 2023.9.29 release prior to the values.schema.json addition.
