### ISSUE TITLE
Unable to deploy multiple versions of the prefect-worker

### ISSUE THREAD

**Issue by gyu11** [PrefectHQ/prefect-helm#272]
**Objective:** I want to deploy workers to various work-pools with different execution environments (e.g. some using GPU node pools).

**Problem:** The current prefect-worker chart doesn't not seem to support this and I am unable to include multiple versions of the prefect-worker chart as a sub-chart in my main prefect helm chart or independently as a separate release of the prefect-worker.

Here is the error I am receiving when trying to include multiple versions of the prefect-worker as a subchart (using the alias prefect-worker-v100-gpu):
```
pathType:ImplementationSpecific]) Error: UPGRADE FAILED: cannot patch "prefect-worker" with kind Deployment: Deployment.apps "prefect-worker" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"worker", "app.kubernetes.io/instance":"prefect", "app.kubernetes.io/name":"prefect-worker-v100-gpu"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Reproducing the issue:**
You should be able to reproduce this issue using a chart with the following `Chart.yaml` and `values.yaml`.

Chart.yaml:
```yaml
apiVersion: v2
name: parent-prefect-chart
description: A Helm chart for workflow orchestration using prefect

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: prefect-server
    version: "2023.11.9"
    repository: https://prefecthq.github.io/prefect-helm
  - name: prefect-worker
    version: "2023.11.9"
    repository: https://prefecthq.github.io/prefect-helm
  - name: prefect-worker
    version: "2023.11.9"
    repository: https://prefecthq.github.io/prefect-helm
    alias: prefect-worker-v100-gpu
```

values.yaml:
```yaml
prefect-server:
  server:
    replicaCount: 2 

prefect-worker:
  worker:
    replicaCount: 2
    apiConfig: server
    config:
      workPool: compute-pool
      type: kubernetes
    serverApiConfig:
      apiUrl: http://prefect-server:4200/api
  role:
    extraPermissions:
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "get", "watch"]

prefect-worker-v100-gpu:
  worker:
    replicaCount: 2
    resources:
      limits:
        cpu: "4"
        memory: 30Gi
      requests:
        cpu: "1"
        memory: 1Gi
    nodeSelector:
      cloud.google.com/gke-accelerator: nvidia-tesla-v100
    apiConfig: server
    config:
      workPool: v100-gpu-compute-pool
      type: kubernetes
    serverApiConfig:
      apiUrl: http://prefect-server:4200/api
  role:
    extraPermissions:
      - apiGroups: [""]
        resources: ["events"]
        verbs: ["list", "get", "watch"]
```

I've also tried to accomplish this object by deploying a prefect-work separately as a release independent of my main prefect parent chart and ran into the following issue:
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: ServiceAccount "prefect-worker" in namespace "prefect" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "prefect-v100-gpu-worker": current value is "prefect"
```
