### ISSUE TITLE
Using Ansible to install Prefect helm chart

### ISSUE THREAD

**Issue by AHulshoff** [PrefectHQ/prefect-helm#319]
I am trying to install Prefect with the helm chart. But unfortunately it fails on configuring the Postgres port. It expects the value to be a number, which is of course understandable. However, when retrieving these values from kubernetes with an Ansible playbook, parameters will always be returned as strings not as integers. This causes an error, even when adding the conversion to an int. This is expected as well, since it is basically Jinja templating.

```
- name: Install Prefect Server helm chart
  kubernetes.core.helm:
    name: prefect-server
    release_namespace: prefect
    create_namespace: true
    update_repo_cache: true
    chart_ref: prefect/prefect-server
    chart_version: 2024.4.18205353
    values:
      service:
        type: LoadBalancer
      postgresql:
        auth:
          enabled: true
          database: prefect
          username: "{{ postgres_usr }}"
          existingSecret: prefect-secret
        containerPorts: 
          postgresql: "{{ svc['port'] | first | int }}"
        externalHostname: "{{ svc['service'] + '.' + svc['namespace'] + '.svc.' + k8s_domain }}"
``` 

This is the error:

> TASK [Install Prefect Server helm chart] 
> **************************************************************************************************************************************************************************
> fatal: [k8s-cp-1]: FAILED! => changed=false 
>   command: /usr/sbin/helm --version=2024.4.18205353 upgrade -i --reset-values --create-namespace -f=/tmp/tmpibz0p6lb.yml prefect-server prefect/prefect-server
>   msg: |-
>     Failure when executing Helm command. Exited 1.
>     stdout: Release "prefect-server" does not exist. Installing it now.
>   
>     stderr: Error: values don't meet the specifications of the schema(s) in the following chart(s):
>     prefect-server:
>     - postgresql.containerPorts.postgresql: Invalid type. Expected: integer, given: string
>   stderr: |-
>     Error: values don't meet the specifications of the schema(s) in the following chart(s):
>     prefect-server:
>     - postgresql.containerPorts.postgresql: Invalid type. Expected: integer, given: string
>   stderr_lines: <omitted>
>   stdout: |-
>     Release "prefect-server" does not exist. Installing it now.
>   stdout_lines: <omitted>
