### ISSUE TITLE
Prefect Worker Job Template not updating in the UI

### ISSUE THREAD

**Issue by Montek30** [PrefectHQ/prefect-helm#346]
Hi guys, I am using the latest feature of using the prefect worker job template as configmap (https://github.com/PrefectHQ/prefect-helm/issues/334) but the job template is not reflecting in the prefect UI. The worker pods are rotating with new config but the UI still has the old configuration.
Helmrelease prefect-worker, version "2024.6.4205506" :
```
      config:
        workPool: cnp-eu-dev-worker-pool
        limit: 20
        baseJobTemplate:
          existingConfigMapName: "cnp-eu-dev-worker" 
```
Configmap:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnp-eu-dev-worker
  namespace: data-platform-prefect
data:
  baseJobTemplate.json: |
    {}
```

Does anyone know if there's anything odd with my config.
