### ISSUE TITLE
Unable to configure securityContext.capabilities

### ISSUE THREAD

**Issue by tmyhu** [PrefectHQ/prefect-helm#352]
It is best practice to drop all capabilities and only add those required. In our clusters we enforce this with policies so I want to add this to my values:
```
server:
  containerSecurityContext:
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
 ```
This fails due to the schema validation which does not appear to be skippable with helm. Can the capabilities node be added to schema in the server and worker helm charts?
