### ISSUE TITLE
Changes to chart with `postgresql.enabled = false` and external postgres break deployment

### ISSUE THREAD

**Issue by ahgraber** [PrefectHQ/prefect-helm#358]
Changes from #341 are breaking my deployment.

Context:  I use [movetokube/postgres-operator: Postgres operator for Kubernetes](https://github.com/movetokube/postgres-operator) to dynamically provision postgres as part of my gitops deployment process.  This operator creates unique auth info in a secret that _does not match the expected format_ of the prefect helm chart.

Prior to that change, I set:

```yaml
  valuesFrom:
    - kind: Secret
      name: &db_secret database-prefect
      valuesKey: DATABASE_NAME
      targetPath: postgresql.auth.database
    - kind: Secret
      name: *db_secret
      valuesKey: LOGIN
      targetPath: postgresql.auth.username
    - kind: Secret
      name: *db_secret
      valuesKey: PASSWORD
      targetPath: postgresql.auth.password
    - kind: Secret
      name: *db_secret
      valuesKey: HOST
      targetPath: postgresql.externalHostname
values:
  ...
  postgresql:
      enabled: true
      useSubChart: false
```

And the helpers picked up the values I was injecting in from the operator's secret at the valid targetPaths.

After #341, this approach does not work because the helm chart _expects_ that there will be a secret named `prefect-server-postgresql-connection` and does not create the secret as it used to based on the injected values.

I'd really appreciate it if the chart supported the use of external postgres while providing details in `postgres.auth` and `postgres.externalHostname` or supported passing the full `postgresql+asyncpg://{username}:{password}@{hostname}/{database}` connection url as an option.

The requirement to use the `prefect-server-postgresql-connection` secret that does not work with my gitops deployments!  Thank you!
