### ISSUE TITLE
prefect-worker initContainer missing securityContext

### ISSUE THREAD

**Issue by tmyhu** [PrefectHQ/prefect-helm#362]
The initContainer `sync-base-job-template` in prefect-worker deployment has no container `securityContext` set and no option to do so in the helm chart.
It would be great to have that added, this config for example seemed to work fine for us:
```
securityContext:
  runAsUser: 1001
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
```
