### ISSUE TITLE
prefect-worker deployment checksum/config issue with existingConfigMapName specified

### ISSUE THREAD

**Issue by k-wolski** [PrefectHQ/prefect-helm#369]
To make sure that prefect-worker pod will be recreated during deployment with `sync-base-job-template` that is going to sync config map with base job template on Prefect Cloud, there is annotation added like this:

```
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```
https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-worker/templates/deployment.yaml#L23

The problem is that `/configmap.yaml` is modified only in a case where `.Values.worker.config.baseJobTemplate.configuration` is provided: https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-worker/templates/configmap.yaml#L1C8-L1C59

In my case, I'm using prefect-worker helm chart as a dependency with some customization on my end - one of this is external config map that is created from template. Because of that `checksum/config` is not changing between deployments.

If think that there should be `if` specified for that, and in case of using `existingConfigMapName`, sha256sum should be calculated from that configMap.
