### ISSUE TITLE
External database credential issues

### ISSUE THREAD

**Issue by adam-brusselback** [PrefectHQ/prefect-helm#441]
I am using your helm chart as a dependency in my application stack that I am deploying into a k8s namespace.
In the same chart I am creating a CNPG cluster for Prefect.

That CNPG cluster creation makes a secret called `goacquire-cluster-prefect-app` with `username` and `password`.

As far as I know, there is absolutely no way to configure the values.yaml to use the values from that secret to put things into the correct properties:
```
prefect-server: 
  postgresql: 
    enabled: false
  secret:
    username: ...
    password: ...
```

I also don't want to have my Postgres password in plain text in a yaml file, considering it is already safe inside a Secret.

So that left me with attempting to create another secret and instructing Prefect to use it:
```
{{{- $secret := (lookup "v1" "Secret" .Release.Namespace "goacquire-cluster-prefect-app") }}
{{- if $secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: prefect-postgres-secret
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  connection-string: {{ printf "postgresql+asyncpg://%s:%s@goacquire-cluster-prefect-rw:5432/app" ($secret.data.username | b64dec) ($secret.data.password | b64dec) | b64enc }}
{{- end }}
```
and:
```
prefect-server: 
  postgresql: 
    enabled: false
  secret:
    create: false
    name: prefect-postgres-secret
```

But since the `goacquire-cluster-prefect-app` doesn't exist yet when I run helm install, if I don't have the `if` statement there there is an error thrown:
```
Error: INSTALLATION FAILED: template: goacquire/templates/prefect-postgres-secret.yaml:12:106: executing "goacquire/templates/prefect-postgres-secret.yaml" at <$secret.data.username>: nil pointer evaluating interface {}.username
```

So I put the `if` in place, and now need to run:
```
helm install...
helm update...
```
to actually get a working cluster. I find this extremely ugly.

I am probably missing something relatively obvious that would make this a lot easier... I just don't know what that is.
Any help would be greatly appreciated.
