### ISSUE TITLE
PREFECT_API_AUTH_STRING should be a Secret Env var, not a clear text Env var in spawned Runs

### ISSUE THREAD

**Issue by raayu83** [PrefectHQ/prefect-helm#442]
Currently in the spawned run pods, PREFECT_API_AUTH_STRING is created as a clear text Environment Variable, visible to anyone with access to the Kubernetes CLI or UI.
For security reasons, this should be based on a Secret, just as with Worker pods and the Server pod.

**Comment by mitchnielsen** [comment]
Hi @raayu83, thanks for reaching out.

In the [Deployment manifest template](https://github.com/PrefectHQ/prefect-helm/blob/3acdb38e877ebbbeeaec29607e4d5ceb26cafab1/charts/prefect-worker/templates/deployment.yaml#L206-L215), the auth string can be taken from a Secret if you provide `worker.basicAuth.existingSecret`. There are some more details available in https://github.com/PrefectHQ/prefect-helm/tree/main/charts/prefect-worker#basic-auth.

Is this what you were looking for?

**Comment by mitchnielsen** [comment]
Ah, thanks for clarifying, and good find.

> The downside is that if for some reason this part of the job template gets lost or not rolled out before running any jobs

You should be able to persist this setting via Helm values:

```yaml
worker:
  config:
    baseJobTemplate:
      configuration: |
       {
         "job_configuration": {
           "job_manifest": {
             "spec": {
               # apply your configuration here
             }
           }
         }
       }

```

https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-worker/values.yaml#L113-L134

Does that address your use case, or are you envisioning something else?
