### ISSUE TITLE
Persistent Volume Not Attaching to Prefect Deployments in Minikube

### ISSUE THREAD

**Issue by zhavir** [PrefectHQ/prefect-helm#443]
Hello,

I'm trying to configure my local instance of Prefect running on a Minikube cluster, but I'm having trouble attaching a persistent volume (pointing to a local host path) to my deployments.

I was able to successfully attach the volume to both the work pool and the server, but it seems this is not enough to ensure the volume is mounted on the generated pods.

Current Helm Configuration
Here is my Helm definition for the worker:

```
namespaceOverride: "prefect"

worker:
  apiConfig: server
  extraEnvVarsCMs: ["prefect-config"]
  config:
    workPool: test
  serverApiConfig:
    apiUrl: http://10.96.22.222:4200/api
  # basicAuth:
  #   enabled: true
  #   authString: "admin:pass"
  extraVolumeMounts:
    - name: local-folder
      mountPath: /mnt/volume
  extraVolumes:
    - name: local-folder
      hostPath:
        path: /host/volume
        type: DirectoryOrCreate
```

**Expected Behavior**
I expect the generated pods from the deployment to have the volume mounted at /mnt/volume, using the local host path /host/volume.

**Actual Behavior**
The volume is attached to the work pool and server, but it is not automatically mounted on the deployment pods that Prefect generates.

**Question**
What configuration do I need to add to ensure the volume is properly mounted on all deployment pods? Is there an additional setting required to propagate the volume to the pods created by the Prefect deployment?

Any help would be greatly appreciated! Thanks in advance.
