### ISSUE TITLE
Can't connect to Server API at http://localhost:4200/api. Check that it's accessible from your machine.

### ISSUE THREAD

**Issue by OliverKleinBST** [PrefectHQ/prefect-helm#476]
Hi

I have a self hosted prefect on Azure Kubernetes and I migrated from Prefect Helm Chart which came with prefect 3.2.0 to the one that comes with prefect 3.2.15.

In the chart there is an update on the API Url configuration. When I migrate my old settings to the new ones I get a problem like
Can't connect to Server API at http://localhost:4200/api. Check that it's accessible from your machine.

## The settings I had in my old setup:
```
global:
  prefect:
    # -- sets PREFECT_API_URL
    prefectApiUrl: http://localhost:4200/api
    # -- sets PREFECT_SERVER_API_HOST
    prefectApiHost: 0.0.0.0

    # -- sets PREFECT_UI_API_URL
    prefectUiApiUrl: ""
    # -- sets PREFECT_UI_URL
    prefectUiUrl: ""
```

To connect to the server I have Nginx Ingress with my public DNS name which I also entered then here

```
server:
  ui_config:
    prefectUiApiUrl: "<mydns>/api"
    # -- sets PREFECT_UI_URL
    prefectUiUrl: "<mydns>"
```

## In the new chart:
 I seem now to be able to configure only a single prefectUiAPiUrl in the server ui_config section which breaks my setup.
