### ISSUE TITLE
Missing Worker Permission for new kubernetes worker in prefect version >=3.4.1

### ISSUE THREAD

**Issue by marcm-ml** [PrefectHQ/prefect-helm#485]
Hey, the new worker using the kopf observer implementation requires some more RBAC permissions. I get this error when running the chart with default values. It seems the worker is still able to run but lacks some permissions. I am not 100% sure if these permissions are actually needed for correct operation. Perhaps there is something running in the observer implementation unnecessarily. @desertaxle Are you able to help out here?

error1

```log
09:12:15.756 | ERROR   | kopf._core.reactor.observation - Request attempt #1/9 failed; will retry: GET https://kubernetes.default.svc/api/v1/namespaces -> APIForbiddenError('namespaces is forbidden: User "system:serviceaccount:prefect:prefect-worker" cannot list resource "namespaces" in API group "" at the cluster scope', {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'namespaces is forbidden: User "system:serviceaccount:prefect:prefect-worker" cannot list resource "namespaces" in API group "" at the cluster scope', 'reason': 'Forbidden', 'details': {'kind': 'namespaces'}, 'code': 403})
```

and error 2

```log
09:12:30.190 | ERROR   | kopf._cogs.clients.watching - Request attempt #1/9 failed; will retry: GET https://kubernetes.default.svc/apis/apiextensions.k8s.io/v1/customresourcedefinitions -> APIForbiddenError('customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:prefect:prefect-worker" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope', {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:prefect:prefect-worker" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope', 'reason': 'Forbidden', 'details': {'group': 'apiextensions.k8s.io', 'kind': 'customresourcedefinitions'}, 'code': 403})
```

Creating these permissions fixes the issue (might be relevant: https://kopf.readthedocs.io/en/stable/deployment/#rbac):

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefect:prefect-worker
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prefect:prefect-worker
subjects:
  - kind: ServiceAccount
    name: prefect-worker
    namespace: prefect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prefect
```
