### ISSUE TITLE
Values schema does not allow resource request/limit for ephemeral storage

### ISSUE THREAD

**Issue by lostkamp** [PrefectHQ/prefect-helm#495]
Hi,

when I try to deploy the chart I get the following error:

```
helm upgrade prefect-server (...)

Release "prefect-server" does not exist. Installing it now.
Error: values don't meet the specifications of the schema(s) in the following chart(s):
prefect-server:
- server.resources.requests: Additional property ephemeral-storage is not allowed
- server.resources.limits: Additional property ephemeral-storage is not allowed
```

My resource values look like this:
```yaml
    # -- the requested resources for the background-services container
    requests:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 100Mi
    # -- the requested limits for the background-services container
    limits:
      cpu: "1"
      memory: 1Gi
      ephemeral-storage: 100Mi
```

Setting requests and limits for `ephemeral-storage` along with CPU and memory is enforced by the Kubernetes admins in our org. Therefore the schema should allow for these fields.

Kubernets docs: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage
