### ISSUE TITLE
Cannot create resource pods when using Dask

### ISSUE THREAD

**Issue by john-jam** [PrefectHQ/prefect-helm#70]
If we define a flow with a Dask task runner and `dask_kubernetes.KubeCluster` as its `cluster_class`, the agent cannot create pods in the cluster with the error:
```
"message":"pods is forbidden: User \"system:serviceaccount:myserviceaccount\" cannot create resource \"pods\" in API group \"\" in the namespace \"mynamespace\"","reason":"Forbidden","details":{"kind":"pods"},"code":403
```

I can obviously add my own `role` and `rolebinding` for the service account created in the `prefect-agent` helm chart but maybe you were planning to support this?

**Comment by john-jam** [comment]
@jamiezieziula FYI, this is the roles I had to add (in addition to the existing role created in the `prefect-agent` template) for the dask KubeCluster class to work:
```yaml
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete" ]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```

**Comment by jamiezieziula** [comment]
Thanks @john-jam - this is a nice-to-have.  I'll look at adding it as a feature!

**Comment by jamiezieziula** [comment]
@john-jam closing the loop - thanks for doing the digging and figuring out what permissions were needed to execute this!  We decided to expose an option to pass additional role permissions to the agent role, rather than supporting specific use-case role permissioning.  On next release, you can provide any additional permissions at this path:
```yaml
role:
  extraPermissions:
    - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```

I did document the specific permissions you mentioned above in the top level readme - thank you!
